# -*- coding: utf-8 -*-
"""DataShield_AI_Redaction_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlROrThwphyxULKMV6bBGznBjvi73uLY
"""

from google.colab import drive
drive.mount('/content/drive')
import os, pprint
PROJECT_DIR = "/content/drive/MyDrive/DataShield_AI"
MODEL_DIR   = f"{PROJECT_DIR}/models/ner-distilbert"
print("Exists?", os.path.isdir(MODEL_DIR))
pprint.pp(os.listdir(MODEL_DIR))

import pandas as pd
import json
import matplotlib.pyplot as plt

drift = json.load(open(f"{MODEL_DIR}/drift_log.json"))
df = pd.json_normalize(drift, record_path=["distribution"], meta=["timestamp"])
df['timestamp'] = pd.to_datetime(df['timestamp'])
df.set_index("timestamp").plot(kind="line", figsize=(12,6))
plt.title("Entity Distribution Over Time")
plt.show()

